travis:
  secure:
    BINSTAR_TOKEN: VCEL/AbHTjwb5u4pSd1OM8Mdn5bKSniVW8LF6Gqk4FQ7ehld47QsKRRiTpwLJSgl9mCUuuSv8Hrd3o0u9iFI7YU6gXIo4RcjnU/04psKiRfmnhqnuFHktRCLlphJXr2B6So3SYKP5k7c9qDxrn6dhCYM85aaKqXADftG9jNprX2ica1RLD31Tt86JTjIlNxAZ1cCRlyWdbasjdWBxvp4UUqcIRmloHYeN3EV7z6IjcsbTdIuKLXulksiAoetB1QC0Gw6SIVGSKvqJdsAEDWRYVF70uIaKS5cQ+6u4Cuw/Hu7osumTyWHl3VolMoud11ngU/6ItZWzhSqk3vbvYoMKLyg/fSfeAdColMe4JNlUqWWFXsVX5tEkh3rEJ1aYhkDr0EHhW8eG2Nit94/auD37zM3NYKkLTfHqLkVVylKzKWKRiT1AX06GpIzXlkyEmv5m5g3UTRSU8nzz2AsA1NqZhRJEjxs/f/8/NKUUziFt3yKVRaCyOXCkQ5m3wmIL4Dpl5JPc2QBTQXwP1Fh/jYfIYLsL2Vz/4jQ7x69T/57BqXIwq17NC/b8yx0iFYEMOMTaZtZnULuP73TvlrsP7+jiET9k/J0gd3kN4kOVC6gkiUT4vujsH4OGAabM7wJ/i1lPwlwZDArxk03E6M7D1itkYjnK9KkKqhSttG0aoLxBrI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
