travis:
  secure:
    BINSTAR_TOKEN: F5OzFLyVV6DLFfMEAkPP2W9bqZONAeOj+Oo0nXsrozar5hrc5tRsaahz1OpIIwlSUdsPZJCG8fouTLJQV2fZ/1iEnzNgdAxvUj9lxMOVtEFDc8BiziT8yNdiVLyxJINH2f1o7rIpjk6KsAmljkUXFx5RWxT6KjTeU65So0RRHktBluw6VCO/XnmgEryopxLCP1ivq+O7KeXWdKy+99XFsMZCr6BTOVTOsNGyWH/biB1wmOHaHNLI970NvraUuqrWWaSe+hxUbqQO8CceL3cfjb7HsWW56wQrz37/16vujKzVftqKDkCqU3Nuv5KbNmucKzee+vIvWfRRED1ZPK9zB2ma2FIZ9ZaOStbVzu2iG+HrYVfjRNlM2Z9gYje6SWxRww7qFVcIC1qq3hJWhC53D/HJNgQXT/LArNtOVJvSzn/AYKPw3YG/R0pcsNzv6qq9ISmTG16wbnDK61kHEXCv3YgPjz39bqWjd3Zoh82hKQHo5dsCjndVg0ULQ6fOdje/8luV5iJP4i/ZDoWGxIUwyaPJQwxLdbTsN5cFIoNHrYJ2hW1dtDPjNCkznSwINwYsH35qnokVANvAPgSit9cOH/Revn8sN58kpVUbJlFEM6CU07THUIDyLF8G5R2s4Oc1+aWGb+SEOZJNrk9/Ua4N399RVJgFnLItQPu/s7dCWRA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
