appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: ECzwXZl6/hSOFieG+VcZwKI9KWRSzFWdaFBgGY4VkcCFNXIgoCAqDSd25znOtSOMQ8zJCkR6TUQPRIPc50VXOZeMMK03PNm0bJMv+BraeIGAmfvKVqUpH1DW1ISt4Gl+ORRiNVatBdCj3L7WBzRFKZSeqt5JlecjUJbAsH1bRPmMonapmRrlajX7VRjJ6CacEziqH12fltwz3nsQOtnUHGbSosmEFWLd7ar4DYX9tjFsNobtCUI+VLln2EQhzLYd1FttJy2oDXuwPySGACXJeKEyT3L3FBpfqYS/Pq2vZgkGyDlYy5+x0+YsGd2XTQwtdhfd/qRW20taN+0DITa1f/mLYJg4zamP62By6ILnO/loACgnorAWkCx8RR7Gc/NHO1/XSicrlAIE/JaRkeu4I7JIc4RiNtP3HEZMKkEzHmKwYTVADCaTWHXTQl0qWz1p+vSZ8GS0acVVlhMrJpFHOPzqRFoE6uHycnwWGxbkB/hIxFpD6rBuUlURSznCUik6VmoEEGhiCWU3xI9o7YFXa0Kr0eYqV1o8JaIkNP5ieZlVlJTLejiCBh1Tv9lFZ1GmIsDPOvhz/UxnEcs68wPnqyCItg+lFRzalHAlqPjMJwZXDgD2ztfAT0qw5UYCOW+E6gd3L2WGfW0/qeGzIy+Exm28//K2g97UNPdPuE5Nbo0=
conda_forge_output_validation: true
